name: maven central 배포
on:
  workflow_call:
    secrets:
      GPG_SECRET:
        required: true
      GPG_PASSPHRASE:
        required: true
      MAVEN_CENTRAL_USERNAME:
        required: true
      MAVEN_CENTRAL_PASSWORD:
        required: true
jobs:
  publish-to-maven-central:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub 리포지토리 체크아웃
        uses: actions/checkout@v4
      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Gradle 애드온 준비하기
        uses: gradle/gradle-build-action@v2
      - name: 프로젝트 빌드
        run: |
          chmod +x gradlew
          ./gradlew --stacktrace build
      - name: 메이븐 센트럴 퍼블리싱
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: |
          export GPG_TTY=$(tty)
          echo "gpg.secret=$GPG_SECRET" >> gradle.properties
          echo "gpg.passphrase=$GPG_PASSPHRASE" >> gradle.properties
          echo "mavenCentralUsername=$MAVEN_CENTRAL_USERNAME" >> gradle.properties
          echo "mavenCentralPassword=$MAVEN_CENTRAL_PASSWORD" >> gradle.properties
          ./gradlew --stacktrace documentify-project:documentify-core:publish
          ./gradlew --stacktrace documentify-project:documentify-plugin:publish
          ./gradlew --stacktrace documentify-project:documentify-mvc:publish
          ./gradlew --stacktrace documentify-project:documentify-reactive:publish
          ./gradlew --stacktrace documentify-starters:documentify-starter-mvc:publish
          ./gradlew --stacktrace documentify-starters:documentify-starter-reactive:publish